### ISSUE TITLE
LootUI not working spamming error

### ISSUE THREAD

**Issue by mauzao9** [albion-packet-hooking/AlbionPacketHandler#6]
[AlbionProcessor.log](https://github.com/albion-packet-hooking/AlbionPacketHandler/files/4912536/AlbionProcessor.log)
[debug.log](https://github.com/albion-packet-hooking/AlbionPacketHandler/files/4912539/debug.log)

That's current the logs about the error, the interface opens and all but the tracking part isn't showing up.

**Comment by albion-packet-hooking** [comment]
Try running it as admin. Otherwise...

No idea. Works on a lot of other computers. Don't have the time to figure out random things on random PCs.

**Comment by mauzao9** [comment]
Yeah I am looking at several things, including building it myself. But is the error normal or not supposed to happen?

I also do not have winpcap right now I have Npcap installed with the winpcap bit option not sure if it would want that by default

**Comment by albion-packet-hooking** [comment]
Not supposed to happen.

Shouldn't need winpcap, it uses sharppcap and should have everything pre-installed without needing any of the other stuff. 

The error is reflection based. I load up "Event Handlers" using reflection so that if someone else wants to add their own event handlers all they have to do is drop their own DLLs in using the supplied base classes.

Probably something to do with the .net version on your computer but I figure as long as you have your windows fairly up to date it'd work.

**Comment by mauzao9** [comment]
I have checked updates, all on .net as is win10 it's all updated, on visual studio trying to build the app it gets stuck on

Exception thrown: 'System.Runtime.InteropServices.SEHException' in SharpPcap.dll, aiming at the line
"            var allDevices = CaptureDeviceList.Instance; "

`   at SharpPcap.Npcap.SafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.Npcap.NpcapDeviceList.Devices()
   at SharpPcap.Npcap.NpcapDeviceList.Refresh()
   at SharpPcap.Npcap.NpcapDeviceList..ctor()
   at SharpPcap.Npcap.NpcapDeviceList.get_Instance()
   at SharpPcap.CaptureDeviceList..ctor()
   at SharpPcap.CaptureDeviceList.get_Instance()
   at AlbionProcessor.PacketHandler.CreateListener() in C:\Users\Max\Source\Repos\AlbionPacketHandler\PacketHandler\PacketHandler.cs:line 266
   at AlbionProcessor.PacketHandler.<Initialize>b__10_0() in C:\Users\Max\Source\Repos\AlbionPacketHandler\PacketHandler\PacketHandler.cs:line 51
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by mauzao9** [comment]
Got my dev to look at it and he gets the same error I get on the app logs. He debugged it and got this:

`Could not load file or assembly 'Photon3Unity3D, Version=4.1.1.17, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)'`

And the log file generates
`2020-07-13 11:40:37,993 [1] ERROR LootUI.MainWindow -    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.AppDomain.Load(AssemblyName assemblyRef)
   at AlbionProcessor.PacketHandler.<>cDisplayClass10_0.<Initialize>b3(String path) in E:\Development\AlbionPacketHandler\PacketHandler\PacketHandler.cs:line 60
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AlbionProcessor.PacketHandler.Initialize() in E:\Development\AlbionPacketHandler\PacketHandler\PacketHandler.cs:line 60
   at AlbionProcessor.PacketHandler..ctor() in E:\Development\AlbionPacketHandler\PacketHandler\PacketHandler.cs:line 40
   at AlbionProcessor.PacketHandler.<>c.<.cctor>b__20_0() in E:\Development\AlbionPacketHandler\PacketHandler\PacketHandler.cs:line 116
   at System.Lazy1.CreateValue()
   at System.Lazy1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AlbionProcessor.AlbionProcessor..ctor() in E:\Development\AlbionPacketHandler\AlbionProcessor\AlbionProcessor.cs:line 11
   at LootUI.MainWindow..ctor() in E:\Development\AlbionPacketHandler\LootUI\MainWindow.xaml.cs:line 30`

**Comment by mauzao9** [comment]
Found the cause of the error, Windows 10 decided to "block" almost every file because it came from "another computer", in properties it had the checkbox to "Unblock", only after doing that that it ran without errors :)

**Comment by albion-packet-hooking** [comment]
Weird. Haven't seen that issue.

I only quickly tossed it up here, didn't have any kind of continuous deployment plan in place. It's a side project and am too busy to put too much time into that other than the reversing aspect.
